apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: devops-issac
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: $REGISTRY/$NAMESPACE/$IMAGE:$TAG
        ports:
        - containerPort: 80
